---
version: '3'
services:
  web:
    build:
      context:  .
    stdin_open: true
    tty: true
    command: /bin/bash
  db:
    build:
      context:  .
    stdin_open: true
    tty: true
    command: /bin/bash
...
